export type SubscriptionPlan = 'free' | 'plus' | 'pro' | 'ultra'
export type SubscriptionStatus = 'active' | 'expired' | 'cancelled' | 'grace_period' | 'paused'
export type PaymentMethod = 'midtrans' | 'google_play' | 'apple_iap' | 'manual'
export type PaymentStatus = 'pending' | 'success' | 'failed' | 'expired' | 'refunded'
export type FileVisibility = 'private' | 'shared' | 'public'
export type ShareStatus = 'active' | 'expired' | 'revoked'
export type UploadStatus = 'pending' | 'uploading' | 'processing' | 'completed' | 'failed' | 'cancelled'
export type NotificationType =
  | 'upload_complete'
  | 'storage_warning'
  | 'subscription_expiring'
  | 'subscription_expired'
  | 'promotion'
  | 'link_accessed'
  | 'security_alert'
  | 'referral_accepted'
  | 'payment_success'
  | 'payment_failed'
export type ReportStatus = 'pending' | 'reviewed' | 'resolved' | 'dismissed'
export type ReportReason = 'illegal_content' | 'spam' | 'copyright' | 'malware' | 'other'
export type AuditAction =
  | 'login'
  | 'logout'
  | 'file_upload'
  | 'file_delete'
  | 'file_move'
  | 'file_rename'
  | 'folder_create'
  | 'folder_delete'
  | 'share_create'
  | 'share_revoke'
  | 'subscription_upgrade'
  | 'subscription_cancel'
  | 'password_change'
  | 'account_delete'
  | 'admin_action'

export type FileCategory = 'image' | 'video' | 'audio' | 'document' | 'archive' | 'other'
export type SortField = 'name' | 'created_at' | 'size' | 'type'
export type SortOrder = 'asc' | 'desc'
export type Platform = 'ios' | 'android' | 'web'
